# Generated by Django 5.0.7 on 2024-08-07 20:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_projectimage_projectvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=cloudinary.models.CloudinaryField(default='www.google.com', max_length=255),
            preserve_default=False,
        ),
    ]
