# Generated by Django 5.0.7 on 2024-08-07 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('images', 'Images'), ('videos', 'Videos')], max_length=6)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='portfolio.project')),
            ],
        ),
        migrations.AddField(
            model_name='projectimage',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='portfolio.tag'),
            preserve_default=False,
        ),
    ]
