# Generated by Django 5.0.7 on 2024-08-07 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_tag_projectimage_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvideo',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_videos', to='portfolio.tag'),
        ),
    ]
